# Generated by Django 3.1.2 on 2020-10-14 04:44

import campaigns.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventurer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(blank=True, null=True)),
                ('note', models.TextField(default=' ')),
                ('order_position', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.BooleanField(default=False)),
                ('tag', models.CharField(default=' ', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='card/')),
                ('name', models.CharField(default=' ', max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.ManyToManyField(blank=True, to='campaigns.Note')),
                ('tags', models.ManyToManyField(blank=True, to='campaigns.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='campaign/')),
                ('title', models.CharField(default=' ', max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('cards', models.ManyToManyField(blank=True, to='campaigns.Card')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=models.SET(campaigns.models.get_sentinel_user), related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=models.SET(campaigns.models.get_sentinel_user), related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('parties', models.ManyToManyField(blank=True, to='adventurer.Party')),
                ('tags', models.ManyToManyField(blank=True, to='campaigns.Tag')),
            ],
        ),
    ]
